name: Publish beta on Modrinth

on:
    push:
        tags: 
          - rc-*

permissions:
    contents: write
  
jobs:        
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check Environment Variables
              run: env
    
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: true
      
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: ${{vars.JAVA_VERSION}}

            - name: Make Gradle Wrapper Executable
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x ./gradlew
            
            - name: Build
              run: ./gradlew clean build
            
            - name: Publish (Modrinth/GitHub)
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: ${{vars.MODRINTH_ID}}
                  modrinth-token: ${{secrets.MODRINTH_TOKEN}}
                
                  name: "(BETA) ${{vars.MOD_NAME}} ${{github.ref_name}}"
                  version-type: beta
                  changelog-file: CHANGELOG.md
                  java: ${{vars.JAVA_VERSION}}
